#!/usr/bin/env bash
# Start and scan timing with 500 generated tasks.
#   scripts/perf.sh            scan timing, plus app start and idle CPU if the release build exists
# The app part opens a Workly window for ~20 s and closes it again.
set -euo pipefail
cd "$(dirname "$0")/.."
export PATH="$HOME/.cargo/bin:$PATH"

WS=/tmp/workly-perf
APP=target/release/bundle/macos/Workly.app/Contents/MacOS/workly-app

rm -rf "$WS" && cp -R fixtures/workspace "$WS"

# 100 tasks in each of the five live fixture projects, ids from 100 up.
statuses=(backlog todo doing review done)
n=0
for p in website-relaunch:WR invoice-extraction:IE ops-dashboard:OPS newsletter-automation:NA support-triage:ST; do
  dir="$WS/projects/${p%%:*}/tasks" key="${p##*:}"
  mkdir -p "$dir"
  for i in $(seq 100 199); do
    n=$((n + 1))
    cat > "$dir/$key-$i-generated-task-$i.md" <<MD
---
id: $key-$i
title: Generated task $i for $key
status: ${statuses[$((i % 5))]}
priority: $((i % 3 + 1))
due: 2026-11-$(printf %02d $((i % 28 + 1)))
tags: [perf, batch-$((i % 7))]
created: 2026-10-01
done_at: null
---
Generated by scripts/perf.sh. Some description text so the body is not empty.

## Updates
- 2026-10-01 09:00 · me: created
MD
  done
done
echo "generated $n tasks in $WS"

echo "== scan (release)"
cargo run --release -q -p workly-core --example scan -- "$WS"

if [ ! -x "$APP" ]; then
  echo "== app: skipped, build it first with: pnpm tauri build"
  exit 0
fi

echo "== app start"
before=$(pgrep -f com.apple.WebKit.WebContent | sort || true)
log=$(mktemp)
WORKLY_WORKSPACE="$WS" "$APP" 2> "$log" &
pid=$!
trap 'kill $pid 2>/dev/null || true; rm -f "$log"' EXIT
for _ in $(seq 100); do
  grep -q "ready after" "$log" && break
  sleep 0.1
done
grep "ready after" "$log" || { echo "no ready line:"; cat "$log"; exit 1; }

echo "== idle CPU (10 s after start, last of 4 samples, 3 s apart)"
sleep 10
webviews=$(comm -13 <(echo "$before") <(pgrep -f com.apple.WebKit.WebContent | sort) | tr '\n' ' ')
args=(-pid "$pid")
for w in $webviews; do args+=(-pid "$w"); done
top -l 4 -s 3 -stats pid,cpu,command "${args[@]}" | awk '/^PID/ { block = "" } { block = block $0 "\n" } END { printf "%s", block }'
